modLoader = "javafml"
loaderVersion = "${fml_version_range}"
license = "${license}"

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${version}" #mandatory
    displayName = "${mod_name}" #mandatory
    displayURL= "${display_url}"
    authors = "${author}" #optional
    description = '''${description}''' #mandatory



[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"