modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU LGPLv3"

[[mods]]
modId="stateobserver" #mandatory
version="${file.jarVersion}" #mandatory
displayName="State Observer" #mandatory
logoFile="examplemod.png" #optional
authors="Favouriteless" #optional
description='''
Observerving blockstate changes over a large area without a performance hit.
'''

[[dependencies.stateobserver]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
